"""add created at field

Revision ID: 0d62bfa36205
Revises: 6b3c6ea62d98
Create Date: 2024-08-03 23:51:35.385022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d62bfa36205'
down_revision: Union[str, None] = '6b3c6ea62d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_file', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_file', 'created_at')
    # ### end Alembic commands ###
