"""init models

Revision ID: 840a096ddbe1
Revises: 
Create Date: 2024-08-03 19:52:27.084114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840a096ddbe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_media_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('link_on_cloud', sa.String(), nullable=True),
    sa.Column('metadata_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata_media_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_uid'), 'audio', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_uid'), table_name='audio')
    op.drop_table('audio')
    op.drop_table('metadata_media_file')
    # ### end Alembic commands ###
